version: '3.9'

services:
  db:
    image: mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: "3233"
       MYSQL_DATABASE: "bagjack"
    
    volumes:
      - data:/var/lib/mysql
      


  web:
    build: .
    ports:
      - "50055:50055"
    volumes:
      - C:/Users/Justin/Documents/PROJECTS/Bagjack/excel:/usr/app/zeiterfassung/excel
      
  
  
        
volumes:
  data:
    external: true


