version: '3.9'

services:
  db:
    image: mysql
    ports:
      - "5000:3306"
    
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: bagjack
      MYSQL_ROOT_PASSWORD: "3233"  
      MYSQL_USER: justin
      MYSQL_PASSWORD: 3233
    
    
    volumes:
      - data:/var/lib/mysql
      


  backend_time:
    build: ./backend
    restart: always
    ports:
      - "50055:50055"
    command: node ./serverZE.js
    volumes:
      - C:/Users/Justin/Documents/PROJECTS/Bagjack/excel:/usr/app/zeiterfassung/excel

  backend_storage:
    build: ./backend
    restart: always
    ports:
      - "50056:50056"
    command: node ./serverST.js

  frontend_storage:
    build: ./storage
    restart: always
    ports:
      - "3000:3000"

    stdin_open: true
    tty: true
      
  
  
        
volumes:
  data:


