version: '3.9'

services:
  db:
    image: mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: "3233"
    
    volumes:
      - data:/var/lib/mysql


  web:
    build: .
    ports:
      - "50055:50055"
    volumes:
      - type: bind 
        source: C:/Users/Justin/Documents/PROJECTS/Bagjack/excel
        target: /usr/app/zeiterfassung/excel
  
  
        
volumes:
  data:
    external: true


