version: '3.9'

services:
  db:
    image: mysql
    ports:
      - "5000:3306"
    
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: bagjack
      MYSQL_ROOT_PASSWORD: "3233"  
      MYSQL_USER: justin
      MYSQL_PASSWORD: 3233
    
    
    volumes:
      - data:/var/lib/mysql
      


  web:
    build: .
    ports:
      - "50055:50055"
    volumes:
      - C:/Users/Justin/Documents/PROJECTS/Bagjack/excel:/usr/app/zeiterfassung/excel
      
  
  
        
volumes:
  data:


